#!/bin/bash

if [ "$1" == "-v" ]; then
	arduino-cli compile -b arduino:avr:uno
elif [ "$1" == "-u" ]; then
	
	arduino-cli compile -b arduino:avr:uno
	arduino-cli upload -b arduino:avr:uno -p /dev/ttyACM0 -v
else
	echo -e "Nenhuma opção fornecida"
fi
